---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: rufus
    name: postgres-pod
spec:
  containers:
    - name: postgress
      image: postgress
      env:
        - name: POSTGRESS_PASSWORD
          value: rufus
        - name: POSTGRES_USER
          value: MYUSER
        - name: POSTGRES_DB
          value: MYDB
      ports:
        - containerPort: 5432
...