---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: rufus
    name: postgres-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    author: rufus
    name: postgres-pod


...