---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: rufus
    name: voting-app-service
spec:
  type: loadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    author: rufus
    name: voting-app-pod

...